build: off
clone_depth: 5
configuration: Release

environment:
  PKG_NAME: chi2comb
  CIBW_TEST_COMMAND: "python -c \"import %PKG_NAME%; import sys; sys.exit(%PKG_NAME%.test())\""
  matrix:
    - platform: x64
      ARCH: x64
      PYTHON: C:\Python36-x64
      CIBW_SKIP: cp27-* cp33-* cp34-* cp35-* *-win32
    - platform: x86
      ARCH: x86
      PYTHON: C:\Python36
      CIBW_SKIP: cp27-* cp33-* cp34-* cp35-* *-win_amd64

install:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - "%PYTHON%\\python.exe -m pip install cibuildwheel>=0.9.1"

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - ci\set-win-path.bat
  - powershell -Command "(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/horta/ci/master/appveyor.bat', 'appveyor.bat')" && appveyor.bat
  - copy "%programfiles%\\chi2comb\\bin\\chi2comb.dll" chi2comb\
  - "%PYTHON%\\python.exe -m cibuildwheel --output-dir wheelhouse"
  - if [%APPVEYOR_REPO_TAG%]==[true] (%PYTHON%\python.exe -m pip install twine && %PYTHON%\python.exe -m twine upload --skip-existing wheelhouse/*)

artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels
